service: yopass
provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  memorySize: 128
  region: eu-west-1
  environment:
    TABLE_NAME: yopass-${opt:stage, sls:stage}
    MAX_LENGTH: 10000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"

package:
  individually: true

functions:
  create:
    handler: bootstrap
    package:
      artifact: bin/function.zip
    events:
      - http:
          method: any
          path: /{proxy+}

resources:
  Resources:
    yopassTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
